import type { Messages } from './types'

/**
 * Default user-facing strings. Every string is overridable per-instance via the
 * `messages` config key, and many are customised per-tenant: do not remove keys.
 * Ported verbatim from the original socket-frontend STRINGS.
 */
export const STRINGS: Messages = {
  // Key kept (tenants override it); default reworded: "Teaches" says what the
  // table shows, where "Skills" reads as the tutor's own attributes.
  skills_label: 'Teaches',
  contractor_enquiry:
    'Please enter your details below to enquire about tutoring with {contractor_name}.',
  enquiry: 'Please enter your details below and we will get in touch with you shortly.',
  contractor_enquiry_button: 'Contact {contractor_name}',
  contractor_details_button: 'Show Profile',
  submit_enquiry: 'Submit Enquiry',
  enquiry_submitted_thanks: 'Enquiry submitted, thank you.',
  enquiry_modal_submitted_thanks:
    'Enquiry submitted, thank you.\n\nYou can now close this window.',
  enquiry_button: 'Get in touch',
  enquiry_title: 'Enquiry',
  grecaptcha_missing: 'This captcha is required',
  required: ' (Required)',
  apt_optional: ' (optional)',
  subject_filter_placeholder: 'Select a subject...',
  filter_summary_single: 'showing 1 result',
  filter_summary_plural: 'showing {count} results',
  location_input_placeholder: 'Postcode or town',
  view_profile: 'View Profile',
  grid_view: 'Grid view',
  list_view: 'List view',
  view_toggle_label: 'Change view',
  // Reviews (ROADMAP §3.1)
  review_count: ({ count }) => (count === 1 ? '1 review' : `${count} reviews`),
  reviews_title: 'What parents say',
  reviews_none: 'No reviews yet',
  reviews_show_all: 'Show all {count} reviews',
  // Rate + availability (ROADMAP §3.2)
  rate_from: 'from {amount}/hr',
  /** Suffix after the rate; the amount is rendered separately so it can be emphasised. */
  rate_per_hour: '/hr',
  next_available: 'Next available {when}',
  free_from: 'Free from {when}',
  rate_from_label: 'From',
  online_lessons: 'Online lessons',
  contact_first_name: 'Contact {name}',
  next_available_none: 'No availability listed',
  filter_online_only: 'Online only',
  filter_rate_any: 'Any price',
  filter_rate_under: 'Under {amount}',
  filter_rate_over: '{amount}+',
  // Upper bound is exclusive, so "under" rather than a "{min}–{max}" range, which
  // would read as including {max} and overlap the next band.
  filter_rate_between: '{min} to under {max}',
  filter_price_label: 'Price',
  filter_remove: 'Remove {label} filter',
  tutor_count_single: '1 tutor',
  tutor_count_plural: '{count} tutors',
  review_hours: '({hours} hours)',
  previous: 'Previous',
  next: 'Next',
  no_tutors_found: 'No tutors found.',
  no_tutors_found_loc: 'No more tutors found near "{location}".',
  no_tutors_found_no_loc: 'No more tutors, unable to locate "{location}".',
  no_tutors_found_rate_limited: 'Too many location lookups, no results.',
  distance_away: '{distance}km away',
  book_appointment_button: 'Book Lesson',
  add_to_lesson: 'Add to Lesson',
  diff_minutes: '{minutes} mins',
  diff_1hour: '1 hour',
  diff_1hour_minutes: '1 hour {minutes} mins',
  diff_hours: '{hours} hours',
  diff_hours_minutes: '{hours} hours {minutes} mins',
  spaces: ({ spaces }) => {
    if (spaces === null) return 'Spaces available'
    if (spaces === 0) return 'No spaces available'
    if (spaces === 1) return '1 space available'
    return `${spaces} spaces available`
  },
  spaces_attending: ({ spaces }) => {
    if (spaces === null) return "You're already attending, more spaces available"
    if (spaces === 0) return "You're already attending, no more spaces available"
    if (spaces === 1) return "You're already attending, 1 more space available"
    return `You're already attending, ${spaces} more spaces available`
  },
  add_existing_students: 'Add your existing Students to the lesson',
  add_new_student: 'Add a new Student to the lesson',
  appointment_not_found: 'Appointment not Found',
  appointment_not_found_id: 'No Appointment found with id {apt_id}.',
  price: 'Price',
  job: 'Job',
  start: 'Start',
  finish: 'Finish',
  location: 'Location',
  not_you_sign_out: 'Not you? sign out',
  added: 'Added',
  assuming_timezone: 'Times are shown in your timezone ({timezone})',
  terms_title: 'Terms and Conditions',
  terms_help: 'I have read and agree to the',
  terms_link: 'terms and conditions',
  loading: 'Loading...',
  contractor_not_found: 'Contractor not Found',
  contractor_not_found_id: 'No Contractor found with id {contractor_id}.',
  // Appointments: search / calendar / booking flow
  // Account check (step 0, before lesson search)
  apt_account_title: 'Do you already have an account?',
  apt_account_intro:
    'Enter your email so we can check. If you already book with us, signing in saves re-entering your details.',
  apt_account_check: 'Continue',
  apt_account_found: 'There is already an account for {email}. Sign in to continue.',
  apt_account_not_found: "We couldn't find an account for {email}. You can book as a new client.",
  apt_continue_as_guest: 'Continue as a new client',
  apt_use_different_email: 'Use a different email',
  apt_skip_account_check: 'Skip and show me the lessons',
  apt_continue_to_search: 'Continue',
  apt_signed_in_as: 'Signed in as {name}',
  apt_search_title: 'Book a lesson',
  apt_search_intro: 'Choose the type of lesson you are looking for to see available dates.',
  apt_service_label: 'Type of lesson',
  apt_service_placeholder: 'All lesson types',
  apt_location_label: 'Location',
  apt_location_placeholder: 'Any location',
  apt_search_button: 'See availability',
  apt_change_search: 'Change',
  apt_next_available: 'Next available lesson',
  apt_no_lessons_day: 'No lessons on this day.',
  apt_no_lessons_month: 'No lessons available in {month}.',
  apt_no_lessons_found: 'No upcoming lessons found',
  apt_no_lessons_found_desc: 'Try a different lesson type or check back soon.',
  apt_no_service_lessons:
    'There are no upcoming {service} lessons right now. Try a different lesson type or check back soon.',
  apt_no_lessons_any: 'There are no upcoming lessons right now. Please check back soon.',
  apt_mode_unavailable: 'None available',
  apt_slots_title: 'Lessons on {date}',
  apt_day_lessons: '{count} lessons available',
  apt_morning: 'Morning',
  apt_afternoon: 'Afternoon',
  apt_evening: 'Evening',
  apt_pick_time: 'Choose a time to see who is available.',
  apt_lessons_at_time: '{count} lessons',
  apt_book_slot: 'Book',
  apt_booking_title: 'Confirm your booking',
  apt_back_to_calendar: 'Back to calendar',
  apt_signin_to_book: 'Sign in to book',
  apt_signin_help: 'You will be asked to sign in with your account so we know who is booking.',
  apt_booked_title: 'Booking confirmed',
  apt_booked_desc: '{student_name} has been added to the lesson.',
  apt_book_another: 'Book another lesson',
  // Delivery modes
  delivery_label: 'How would you like the lesson?',
  delivery_any: 'Any',
  delivery_online: 'Online',
  delivery_in_person: 'In person',
  delivery_online_help: 'Taught over video call',
  delivery_in_person_help: 'At one of our venues',
  apt_address_label: 'Your address or postcode',
  apt_address_placeholder: 'e.g. EC1R 4TD or Highgate',
  apt_address_required: 'Enter your postcode so we can show venues near you.',
  apt_radius_label: 'Within',
  apt_online_no_travel: 'No travel needed',
  apt_location_not_found: "We couldn't find \"{location}\". Try a postcode or town.",
  distance_away_miles: '{distance} miles away',
  // Inline account creation (guest booking)
  apt_your_details: 'Your details',
  apt_guest_intro:
    'Tell us who is booking and who the lesson is for. We will set up your account from these details.',
  apt_your_name: 'Your name',
  apt_your_email: 'Email address',
  apt_your_phone: 'Phone number',
  apt_student_name: "Student's name",
  apt_student_help: 'Who is the lesson for?',
  apt_confirm_booking: 'Confirm booking',
  apt_details_continue: 'Continue',
  apt_booking_for: 'Booking for {student_name}',
  apt_have_account: 'Already have an account?',
  apt_sign_in_instead: 'Sign in',
  apt_create_account_instead: 'Book as a new client',
  apt_field_required: 'This field is required',
  apt_email_invalid: 'Please enter a valid email address',
  apt_account_created:
    "We've created your account and emailed you a link to manage your bookings.",
  // Booking flow shell: stepper + summary rail
  apt_step_time: 'Day & time',
  apt_step_time_intro: 'Pick a day to see the available lesson times.',
  apt_step_details_intro: 'Tell us who is booking and who the lesson is for.',
  apt_step_review_intro: 'Check the details and accept the cancellation policy.',
  apt_step_payment_intro: 'Pay securely to confirm your place.',
  apt_step_confirmed: 'Confirmation',
  apt_summary_lesson: 'Lesson',
  apt_summary_date: 'Date & time',
  apt_summary_location: 'Location',
  apt_summary_student: 'Student',
  apt_summary_price: 'Price',
  // Checkout: terms, payment, confirmation
  apt_step_details: 'Your details',
  apt_step_review: 'Review',
  apt_step_payment: 'Payment',
  apt_order_summary: 'Booking summary',
  apt_total_due: 'Total due',
  apt_paid: 'Paid',
  apt_cancellation_policy: 'Cancellation policy',
  apt_cancellation_policy_link: 'Read the full policy',
  // Split so the link can be rendered as an element between the two halves.
  apt_accept_terms_before: 'I accept the',
  apt_accept_terms_after: 'and the cancellation policy',
  apt_accept_terms_plain: 'I accept the cancellation policy',
  apt_must_accept_terms: 'Please accept the terms to continue',
  apt_continue_to_payment: 'Continue to payment',
  apt_pay_now: 'Pay {amount} and confirm',
  apt_card_details: 'Card details',
  apt_card_number: 'Card number',
  apt_card_expiry: 'Expiry',
  apt_card_cvc: 'CVC',
  apt_card_name: 'Name on card',
  apt_use_saved_card: 'Use saved card',
  apt_saved_card_label: '{brand} ending {last4}',
  apt_use_new_card: 'Use a different card',
  apt_save_card: 'Save this card for future bookings',
  apt_payment_secure: 'Payments are processed securely. We never store your card details.',
  apt_payment_failed: 'Payment failed',
  apt_seat_held: 'We are holding this place for you for the next {minutes} minutes.',
  apt_confirmed_title: 'Your lesson is booked',
  apt_confirmed_desc: '{student_name} is booked onto {service_name}.',
  apt_confirmed_email: "We've emailed your confirmation and receipt.",
  apt_confirmed_email_to: "We've emailed your confirmation and receipt to {email}.",
  apt_add_to_calendar: 'Add to calendar',
  apt_view_receipt: 'View receipt',
  apt_done: 'Done',
  apt_back: 'Back',
  // Manage bookings
  bookings_title: 'Your bookings',
  bookings_none: 'No upcoming lessons',
  bookings_none_desc: 'Lessons you book will appear here.',
  bookings_cancel: 'Cancel booking',
  bookings_cancel_confirm: 'Cancel this lesson for {student_name}?',
  bookings_cancel_yes: 'Yes, cancel it',
  bookings_cancel_keep: 'Keep the booking',
  bookings_cancelled: 'Booking cancelled.',
  bookings_cannot_cancel: 'This lesson can no longer be cancelled online.',
  bookings_free_until: 'Free cancellation until {date}',
  nav_book: 'Book a lesson',
  nav_my_bookings: 'My bookings',
}

export const MODES = ['tutors', 'enquiry', 'enquiry-modal', 'appointments'] as const
// `history` was removed in v2: it only works on hosts with an SPA catch-all (a
// drop-in widget can't assume that), so it 404s on refresh. `hash` is safe on any
// host; `memory` touches the URL not at all (no deep-linking).
export const ROUTER_MODES = ['hash', 'memory'] as const

export const DEFAULT_COMPANY_OPTIONS = {
  display_mode: 'grid' as const,
  pagination: 100,
  router_mode: 'hash' as const,
  show_hours_reviewed: true,
  show_labels: true,
  show_location_search: true,
  show_stars: true,
  show_subject_filter: true,
  sort_on: 'name',
}
